### ISSUE TITLE
Functionality Lacking by Default on System Installs of NSO

### ISSUE THREAD

**Issue by gneff** [NSO-developer/ipython-superuser#2]
The issue referred to here [here](https://github.com/NSO-developer/ipython-superuser#ipython-superuserpy-not-found) regarding ipython-superuser.py not being found appears to be nothing but a symptom of ipython-superuser being run in a system install.  

As suggested in the link, this problem can be kludged around by hacking the ipython-superuser.cli file by providing a fully-qualified file path, instead of the default, relative path - example:
```
          <args>-i /opt/ncs/packages/ipython-superuser/python/ipython-superuser.py</args>
          <options>
            <uid>user</uid>
            <gid>user</gid>
          </options>
        </exec>
      </callback>
    </cmd>
  </operationalMode>
  <configureMode>
    <cmd name="ipython">
      <info>Run IPython</info>
      <help>Run IPython</help>
      <callback>
        <exec>
          <osCommand>ipython</osCommand>
          <args>-i /opt/ncs/packages/ipython-superuser/python/ipython-superuser.py</args>
```
I'm uncertain where the solution lies, but it seems some exception handling to identify a system install would be in order.

**Comment by janlindblad** [comment]
This is a tool for debugging -- don't use it on system installs. As pointed out in the README file, it breaks security!
